# Generated by Django 4.0.4 on 2022-04-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='source',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
    ]
