# Generated by Django 4.0.4 on 2022-04-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_news_created_at_remove_news_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='link',
            new_name='url',
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
