# Generated by Django 4.0.4 on 2022-04-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_link_news_url_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
